"""
Software Developer & Lead Code Review AI Agent for Statsfirm Co.
Responsible for:
- Desarrollo en Feature Branch bajo GitFlow (Task_DesarrolloGitFlow).
- Apertura de PR y Peer Code Review automatizado (Task_PullRequestReview).
- Corrección de código y erradicación de deuda técnica (Task_FixCodeQuality).
- Enforzamiento estricto de Clean Code, PEP 8, y principios SOLID.
"""

from typing import Any, Dict, List
import re
try:
    from .base_agent import BaseAgent, AgentTask, AgentResult, AutonomyLevel, ExecutionStatus
except (ImportError, ValueError):
    from base_agent import BaseAgent, AgentTask, AgentResult, AutonomyLevel, ExecutionStatus


class SoftwareDeveloperAgent(BaseAgent):
    """
    Autonomous AI Agent executing full-stack software development and peer code review.
    """

    def __init__(self) -> None:
        system_prompt = (
            "Eres el Agente Senior de Desarrollo de Software y Code Review de Statsfirm Co. "
            "Escribes código limpio, modular y tipado en Python (PEP 8) y Java (Google Style). "
            "Aplicas SOLID, DRY y KISS con rigor absoluto. En cada Pull Request auditas complejidad "
            "ciclomática, presencia de antipatrones (God Object, Magic Numbers) y cobertura de pruebas. "
            "Si detectas vulnerabilidades críticas de seguridad SAST, bloqueas el merge y alertas."
        )
        super().__init__(
            name="Software_Developer_CodeReview_AI",
            role="Lead Software Developer & Code Reviewer",
            autonomy_level=AutonomyLevel.LEVEL_3_CONDITIONAL,
            system_prompt=system_prompt
        )
        self.register_tool("pep8_linter", self._lint_python_code)
        self.register_tool("pr_reviewer", self._review_pull_request)

    def _lint_python_code(self, source_code: str) -> List[str]:
        """Static inspection for PEP 8 and Clean Code violations."""
        issues: List[str] = []
        if re.search(r'except\s*:', source_code):
            issues.append("Violación PEP 8: Captura de excepción genérica (bare except). Use 'except Exception:'.")
        if re.search(r'print\(', source_code):
            issues.append("Clean Code: Uso de 'print' detectado. Reemplace por módulo estándar 'logging'.")
        if re.search(r'[0-9]{4,}', source_code) and "PORT" not in source_code:
            issues.append("Antipatrón: Magic Numbers detectados sin constante nombrada.")
        return issues

    def _review_pull_request(self, pr_diff: str) -> Dict[str, Any]:
        """Automated peer review analysis."""
        lint_issues = self._lint_python_code(pr_diff)
        is_approved = len(lint_issues) == 0
        return {
            "approved": is_approved,
            "lint_issues": lint_issues,
            "suggested_fixes": ["Extraer constantes", "Agregar docstrings Google format"] if not is_approved else []
        }

    def execute(self, task: AgentTask) -> AgentResult:
        """Execute software development or PR code review."""
        logs = [f"Iniciando tarea de ingeniería de software: {task.title}"]
        payload = task.payload
        action = payload.get("action", "CODE_REVIEW")

        if action == "CODE_REVIEW":
            diff_code = payload.get("code_diff", "def calculate():\n    print('calculando')\n    return 42000")
            review_result = self._review_pull_request(diff_code)
            logs.append(f"Revisión de PR finalizada: Aprobado={review_result['approved']}")

            return AgentResult(
                task_id=task.task_id,
                agent_name=self.name,
                status=ExecutionStatus.SUCCESS if review_result["approved"] else ExecutionStatus.FAILURE,
                output={
                    "pr_status": "MERGE_READY" if review_result["approved"] else "CHANGES_REQUESTED",
                    "review_details": review_result
                },
                logs=logs
            )
        else:
            # Code implementation flow
            feature_spec = payload.get("feature_spec", "Implementar conector de ingesta REST")
            logs.append(f"Implementando feature branch: {feature_spec}")
            
            output_code = (
                "# Generated by SoftwareDeveloperAgent\n"
                "from typing import Dict, Any\n"
                "import logging\n\n"
                "logger = logging.getLogger(__name__)\n\n"
                "class FeatureService:\n"
                "    \"\"\"Service implementing feature specifications.\"\"\"\n"
                "    def process(self, payload: Dict[str, Any]) -> bool:\n"
                "        logger.info('Processing feature service payload.')\n"
                "        return True\n"
            )

            return AgentResult(
                task_id=task.task_id,
                agent_name=self.name,
                status=ExecutionStatus.SUCCESS,
                output={
                    "feature_branch": "feature/ASTF-AUTONOMOUS-DEV",
                    "generated_code": output_code,
                    "unit_tests_included": True
                },
                logs=logs
            )
